language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
matrix:
  include:
    - elixir: 1.7
      otp_release: 21.0
      env: COWBOY_VERSION=2.0
    - elixir: 1.8
      otp_release: 21.0
      env: COWBOY_VERSION=2.0
    - elixir: 1.9
      otp_release: 22.0
      env: COWBOY_VERSION=2.0
    - elixir: 1.7
      otp_release: 21.0
      env: COWBOY_VERSION=1.0
    - elixir: 1.8
      otp_release: 21.0
      env: COWBOY_VERSION=1.0
    - elixir: 1.9
      otp_release: 22.0
      env: COWBOY_VERSION=1.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test
  - cd installer && elixir -S mix test
  - cd ../assets && npm install && npm test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
cache:
  directories:
  - assets/node_modules
