language: erlang
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir/tree/v0.13.1
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=all mix test
