language: erlang
otp_release:
  - 17.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v0.15.1.zip
  - unzip -d elixir v0.15.1.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
