language: erlang
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.14.2 && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - mix test
