language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.4
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.4
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.4
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.4
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.4
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.4
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.5
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.5
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.5
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.5
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.5
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.5
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.6
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 19.3
      elixir: 1.6
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.6
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.0
      elixir: 1.6
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.6
      env:
       - COWBOY_VERSION=1.0 ELIXIR_ASSERT_TIMEOUT=2000
    - otp_release: 20.1
      elixir: 1.6
      env:
       - COWBOY_VERSION=2.0 ELIXIR_ASSERT_TIMEOUT=2000
sudo: false
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test
  - cd installer && mix test
  - cd ../ && npm install && npm test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
