language: erlang
services:
  - redis-server
otp_release:
  - 17.1
sudo: false
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.2.zip
  - unzip -d elixir v1.0.2.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
